dateModified: 1562954122
email:
  fromEmail: ''
  fromName: ''
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  08a311d5-c01b-47f1-a65a-99fb0eda26a9:
    name: 'Site Info'
  31d733d0-a56f-450d-abc6-076051bfa12c:
    name: Common
fields:
  3ca498bb-699a-4c66-8b64-10f2d0352bd7:
    name: 'Default social image'
    handle: defaultSocialImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:05a7fe50-fe04-4676-881c-1da5f01efc97'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:05a7fe50-fe04-4676-881c-1da5f01efc97'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: '1'
      selectionLabel: 'Add an image'
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 08a311d5-c01b-47f1-a65a-99fb0eda26a9
  5e067aa5-5ffc-489f-9731-0cf95720c7e9:
    name: Body
    handle: body
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: Standard.json
      purifierConfig: ''
      cleanupHtml: true
      removeInlineStyles: '1'
      removeEmptyTags: '1'
      removeNbsp: '1'
      purifyHtml: '1'
      columnType: text
      availableVolumes: '*'
      availableTransforms: '*'
    contentColumnType: text
    fieldGroup: 31d733d0-a56f-450d-abc6-076051bfa12c
  87525a67-4623-47cb-83f8-7170a1c4bf1a:
    name: Image
    handle: image
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:05a7fe50-fe04-4676-881c-1da5f01efc97'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:05a7fe50-fe04-4676-881c-1da5f01efc97'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: ''
      selectionLabel: 'Add an image'
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 31d733d0-a56f-450d-abc6-076051bfa12c
  bae42bbf-087b-4e77-8a52-3fb4a7de96e5:
    name: 'Default meta description'
    handle: defaultMetaDescription
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: '1'
      initialRows: '2'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 08a311d5-c01b-47f1-a65a-99fb0eda26a9
globalSets:
  7f0a40b2-94e9-43de-b432-70c353387864:
    name: 'Site Info'
    handle: siteInfo
    fieldLayouts:
      85c9ee20-0813-4948-b1f7-aa0b0c88e2da:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              3ca498bb-699a-4c66-8b64-10f2d0352bd7:
                required: false
                sortOrder: 1
              bae42bbf-087b-4e77-8a52-3fb4a7de96e5:
                required: false
                sortOrder: 2
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
sections:
  075ee198-f93d-4c3d-93a8-2573adcfcc93:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    siteSettings:
      31bf2615-8aea-4758-8bd6-8e694982be63:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: ''
    entryTypes:
      ab7dea31-4b1e-4e6e-969e-3f39a42d7729:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: ''
        titleFormat: '{section.name|raw}'
        sortOrder: 1
        fieldLayouts:
          9cc4e4ee-51e3-4783-96d2-f368e0509270:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  5e067aa5-5ffc-489f-9731-0cf95720c7e9:
                    required: false
                    sortOrder: 1
    propagationMethod: all
siteGroups:
  aeb26bbe-f94b-4418-90f5-0904aa07687c:
    name: 'Craft Boilerplate'
sites:
  31bf2615-8aea-4758-8bd6-8e694982be63:
    siteGroup: aeb26bbe-f94b-4418-90f5-0904aa07687c
    name: 'Craft Boilerplate'
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: '@web/'
    sortOrder: 1
    primary: true
system:
  edition: solo
  live: true
  name: 'Craft Boilerplate'
  timeZone: America/Los_Angeles
  schemaVersion: 3.2.14
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  05a7fe50-fe04-4676-881c-1da5f01efc97:
    name: Images
    handle: img
    type: craft\volumes\Local
    hasUrls: true
    url: '@web/assets/uploads/img/'
    settings:
      path: '@webroot/assets/uploads/img/'
    sortOrder: 1
